name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: exit 2
      - name: Run a multi-line script
        if: always()
        run: |
          printenv
          echo "============================"
          echo '${{ github }}'
          echo "============================"    
          echo '${{ job.status }}'
          echo "============================"  
          if '${{ job.status }}' == "failure" ;then
            echo "fail" 
          elae
            echo "ok"
          fi
          echo "============================" 
